/* ---------- questions ---------- */
const LEVELS = [
  { id:1, op:'-', d:2, eq:'42 − 7', desc:'Two digits take away one, crossing a ten' },
  { id:2, op:'-', needs:[1], d:2, eq:'42 − 17', desc:'Two digits take away two, with a borrow' },
  { id:7, op:'-', needs:[2], d:3, eq:'112 − 25', desc:'Crossing back under a hundred' },
  { id:4, op:'+', d:1, eq:'8 + 5', desc:'Two single digits, bridging through ten' },
  { id:5, op:'+', needs:[4], d:2, eq:'27 + 15', desc:'Two digits plus two, with a carry' },
  { id:6, op:'+', needs:[5], d:3, eq:'87 + 25', desc:'Crossing a hundred' },
  { id:8, op:'w', grp:'chain', d:2, eq:'2 + 6 − 5', desc:'A long chain of + and −, worked left to right', also:['mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genChain },
  { id:9, op:'w', grp:'chain', needs:[8], d:3, eq:'1 + 9 + 2 + 8', desc:'Chains that simplify by grouping — into tens, ± pairs, or terms that cancel', also:['mbg-winter-2023-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genPairs },
  { id:79, op:'w', grp:'chain', needs:[9], src:'mbg-winter-2024', d:3, eq:'1 + 49 + 2 + 48', desc:'Numbers that pair up into a round fifty, then used', also:['mbg-winter-2023-2'], gen:genFifty },
  { id:99, op:'w', grp:'chain', needs:[8], src:'mbg-winter-2023', d:3, eq:'86 − (51 − 5)', desc:'Brackets first — or see what each bracket is short of 100', gen:genBrackets },
  { id:83, op:'w', grp:'chain', needs:[8], src:'mbg-winter-2024', d:2, eq:'(…) · 0', desc:'One bracket comes to 0, so the long one needs no working', gen:genZeroFac },
  { id:50, op:'w', grp:'chain', needs:[9], d:5, eq:'Плюс или минус', desc:'Choose the signs in a run — how many can be minus', also:['mbg-autumn-2022-2'], gen:genSigns },
  { id:74, op:'w', grp:'chain', needs:[59], grade:3, d:2, eq:'Знакът ◎', desc:'A new sign, defined by an example, then used', gen:genCircOp },
  { id:59, op:'w', grp:'chain', needs:[9], grade:3, d:2, eq:'20 − 2 · 5', desc:'Multiplication first, then + and − left to right', gen:genMulMix },
  { id:61, op:'w', grp:'chain', needs:[59], grade:3, d:2, eq:'… · 0 …', desc:'A long expression where every product with a 0 is 0', gen:genZeros },
  { id:77, op:'w', grp:'chain', needs:[59], grade:3, d:3, eq:'Изтрих и записах', desc:'Numbers rewritten in two steps, then added', gen:genRewrite },
  { id:63, op:'w', grp:'chain', needs:[59], grade:3, d:4, eq:'Два знака', desc:'Which two different signs make the equality true', gen:genTwoSigns },
  { id:36, op:'w', grp:'count', d:3, eq:'Бонбони', desc:'Ways to share sweets so everyone gets one', also:['mbg-autumn-2024-2'], gen:genCandy },
  { id:12, op:'w', grp:'count', d:3, eq:'Колко? Сбор?', desc:'How many — or the sum — of a range given by a condition', also:['mbg-winter-2023-2', 'mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2024-2', 'mbg-autumn-2025-2', 'mbg-winter-2024-2'], gen:genCount },
  { id:25, op:'w', grp:'count', needs:[12], d:4, eq:'Колко вторника?', desc:'A weekday across a run of days — two answers', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2025-2'], gen:genWeekday },
  { id:24, op:'w', grp:'count', needs:[12], d:4, eq:'Колко сбора?', desc:'How many different results two numbers can make', also:['mbg-winter-2023-2', 'mbg-autumn-2025-2'], gen:genSums },
  { id:55, op:'w', grp:'count', needs:[12], d:4, eq:'Преброй цифрата', desc:'How often one digit turns up across a run of numbers', also:['mbg-autumn-2020-2'], gen:genDigitRun },
  { id:16, op:'w', grp:'count', needs:[12,2], d:5, eq:'Вместо ?', desc:'How many digits make the statement false', also:['mbg-winter-2023-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2025-2', 'mbg-winter-2024-2'], gen:genIneq },
  { id:80, op:'w', grp:'count', needs:[12], src:'mbg-winter-2024', d:2, eq:'Кои от числата?', desc:'Try each of a few given numbers in the box — the edge is the trap', gen:genPickFit },
  { id:101, op:'w', grp:'count', needs:[36], src:'mbg-winter-2023', d:4, eq:'Оцвети квадратчетата', desc:'Colour a row so no two neighbours match — how many ways', gen:genPaintRow },
  { id:65, op:'w', grp:'count', needs:[24], grade:3, d:3, eq:'Колко двуцифрени?', desc:'How many different results two two-digit numbers can make', gen:genSumsTwo },
  { id:51, op:'w', grp:'num', d:3, eq:'Десетици', desc:'A number said in tens, ones and hundreds', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2'], gen:genTens },
  { id:13, op:'w', grp:'num', d:3, eq:'Най-малкото', desc:'Smallest two-digit, largest one-digit, then compare', also:['mbg-winter-2023-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genNamed },
  { id:53, op:'w', grp:'num', needs:[13], d:4, eq:'Трицифрени', desc:'The smallest or largest three-digit number that fits a condition', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2'], gen:genThreeDig },
  { id:46, op:'w', grp:'num', needs:[13], d:4, eq:'Подреди', desc:'Place the numbers so a chain of inequalities holds', also:['mbg-autumn-2022-2'], gen:genOrder },
  { id:35, op:'w', grp:'num', needs:[13], d:4, eq:'Две двуцифрени', desc:'Two different two-digit numbers with a given sum', also:['mbg-autumn-2024-2'], gen:genTwoDig },
  { id:44, op:'w', grp:'num', needs:[8], d:4, eq:'Зачеркни', desc:'Cross out one digit to make it true', also:['mbg-autumn-2023-2'], gen:genCross },
  { id:49, op:'w', grp:'num', needs:[13], d:4, eq:'Кратни', desc:'The smallest count that splits into equal parts both ways', also:['mbg-autumn-2022-2', 'mbg-winter-2024-2'], gen:genMultiple },
  { id:18, op:'w', grp:'num', d:4, eq:'Сбор на цифрите', desc:'How many two-digit numbers have a given digit sum', also:['mbg-autumn-2020-2', 'mbg-autumn-2023-2', 'mbg-autumn-2025-2', 'mbg-winter-2024-2', 'kms-2025-2'], gen:genDigits },
  { id:45, op:'w', grp:'num', needs:[13], d:4, eq:'Четири карти', desc:'Arrange four digits for the smallest difference', also:['mbg-autumn-2023-2'], gen:genCards },
  { id:23, op:'w', grp:'num', needs:[13], d:4, eq:'□△ − 9', desc:'Digits standing in for a two-digit number', also:['mbg-autumn-2025-2'], gen:genPlace },
  { id:54, op:'w', grp:'num', d:5, eq:'Судоку', desc:'Four by four: every row, column and box holds 1 to 4 once', also:['mbg-autumn-2020-2'], gen:genSudoku },
  { id:89, op:'w', grp:'num', needs:[23], src:'mbg-winter-2024', d:4, eq:'C + 1A + B7', desc:'Letters for digits, where only one tens digit can work', gen:genLetters },
  { id:93, op:'w', grp:'num', needs:[13], src:'kms-2025', d:3, eq:'Последователни', desc:'Two numbers in a row, from a sum given in words', gen:genConsec },
  { id:60, op:'w', grp:'num', needs:[53], grade:3, d:3, eq:'Цифрите', desc:'The digits of the smallest or largest three-digit number that fits', gen:genDigProd },
  { id:66, op:'w', grp:'num', needs:[59], grade:3, d:3, eq:'Цифрата на единиците', desc:'Two numbers a set distance apart — which digits their product can end in', gen:genOddProd },
  { id:76, op:'w', grp:'num', needs:[59], grade:3, d:3, eq:'Кое не е избрано?', desc:'Leave one number out so the rest add to a multiple — maybe two ways', gen:genDropOne },
  { id:67, op:'w', grp:'num', needs:[60], grade:3, d:4, eq:'Произведение на цифрите', desc:'The largest or smallest three-digit number by its digits\' product — 0 counts', gen:genDigSum },
  { id:64, op:'w', grp:'num', needs:[44, 59], grade:3, d:5, eq:'Изтрий цифри', desc:'Erase three digits from a product to reach a number', gen:genEraseMul },
  { id:82, op:'w', grp:'seq', needs:[27], src:'mbg-winter-2024', d:4, eq:'0, 3, 6, …, x', desc:'The last number of a run, from how many digits it takes', also:['mbg-winter-2023-2'], gen:genStepDig },
  { id:86, op:'w', grp:'seq', src:'mbg-winter-2024', d:3, eq:'Пирамида от кутии', desc:'Rows of boxes that grow by the same amount each time', gen:genPyramid },
  { id:94, op:'w', grp:'seq', src:'kms-2025', d:3, eq:'КОЛЕДАКОЛЕДА…', desc:'Which letter stands at a place in a word written over and over', gen:genWordPos },
  { id:95, op:'w', grp:'seq', needs:[27], src:'kms-2025', d:4, eq:'25, 24, 21, 16, 9, ?', desc:'A run whose steps grow by the same amount', gen:genDiffSeq },
  { id:27, op:'w', grp:'seq', d:4, eq:'Пропуснатите', desc:'Find the rule, fill the gaps — then read what is asked', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2023-2', 'mbg-autumn-2024-2'], gen:genMissing },
  { id:26, op:'w', grp:'seq', d:4, eq:'Редица', desc:'Smaller on the left, bigger on the right', also:['mbg-autumn-2025-2'], gen:genSeq },
  { id:11, op:'w', grp:'find', d:3, eq:'6 − ◯', desc:'Find the hidden number — or two of them — then use it', also:['mbg-winter-2023-2', 'mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genBox },
  { id:15, op:'w', grp:'find', d:4, eq:'Кое изтрих?', desc:'Spot the number a few more — or a few less — than another', also:['mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genErase },
  { id:29, op:'w', grp:'find', needs:[11], d:4, eq:'Плодове', desc:'Three fruit, three totals — find one from the others', also:['mbg-autumn-2021-2', 'mbg-autumn-2024-2'], gen:genFruitEq },
  { id:37, op:'w', grp:'find', needs:[11], d:5, eq:'Фигури', desc:'Add the fewest shapes to make two counts match', also:['mbg-autumn-2024-2'], gen:genShapes },
  { id:100, op:'w', grp:'find', needs:[11], src:'mbg-winter-2023', d:4, eq:'Магически квадрат', desc:'One number spoils the magic square: find what it should be', gen:genMagic },
  { id:81, op:'w', grp:'find', needs:[11], src:'mbg-winter-2024', d:3, eq:'88 − ■ = 88 − 11', desc:'The box read off an equality, then used', gen:genSameSub },
  { id:92, op:'w', grp:'find', needs:[30], src:'kms-2025', d:2, eq:'Най-малкото умаляемо', desc:'The smallest a number can be, given a difference — 0 counts', gen:genMinuend },
  { id:68, op:'w', grp:'find', needs:[11, 53], grade:3, d:3, eq:'Числото A', desc:'The one number from given digits that makes an inequality true', gen:genDigIneq },
  { id:75, op:'w', grp:'find', needs:[11], grade:3, d:4, eq:'Кръстът', desc:'Rows and columns multiply to the shaded numbers — find the one missing', gen:genProdGrid },
  { id:28, op:'w', grp:'word', d:2, eq:'Ябълки и круши', desc:'Count two groups, then add to reach a difference', also:['mbg-autumn-2024-2'], gen:genFruit },
  { id:38, op:'w', grp:'word', d:3, eq:'Моливи', desc:'Colours counted by what they are not', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-winter-2024-2'], gen:genPencils },
  { id:39, op:'w', grp:'word', d:3, eq:'Не достигат', desc:'Short by so many — so how many are there now?', also:['mbg-autumn-2023-2', 'mbg-winter-2024-2'], gen:genShort },
  { id:47, op:'w', grp:'word', needs:[2], d:3, eq:'Три щайги', desc:'A total, a part of it, and a gap between the rest', also:['mbg-autumn-2022-2'], gen:genCrates },
  { id:14, op:'w', grp:'word', d:3, eq:'Нов сбор', desc:'Every addend changes by the same amount', also:['mbg-autumn-2025-2'], gen:genGrow },
  { id:10, op:'w', grp:'word', needs:[5], d:3, eq:'С колко?', desc:'How much bigger one sum is than the other', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genCmp },
  { id:30, op:'w', grp:'word', needs:[10], d:3, eq:'Умаляемо', desc:'Naming the parts of a sum and a difference', also:['mbg-winter-2023-2', 'mbg-autumn-2024-2'], gen:genTerm },
  { id:57, op:'w', grp:'word', d:4, eq:'Класирането', desc:'Who beat whom — and how many are above someone', also:['mbg-autumn-2020-2'], gen:genRank },
  { id:48, op:'w', grp:'word', needs:[47], d:4, eq:'Два езика', desc:'Two groups that overlap — who is counted twice', also:['mbg-autumn-2022-2'], gen:genBoth },
  { id:42, op:'w', grp:'word', d:4, eq:'Котките', desc:'Two cats and one box of food between them', also:['mbg-autumn-2023-2'], gen:genCats },
  { id:43, op:'w', grp:'word', d:4, eq:'Монети', desc:'The one amount a handful of coins cannot pay', also:['mbg-winter-2023-2', 'mbg-autumn-2023-2'], gen:genCoins },
  { id:17, op:'w', grp:'word', needs:[2], d:4, eq:'Сбор и разлика', desc:'A number given by how far it sits from another', also:['mbg-autumn-2022-2', 'mbg-autumn-2025-2'], gen:genSumDiff },
  { id:58, op:'w', grp:'word', d:5, eq:'Охлювът', desc:'Up by day, back by night — when the top is reached', also:['mbg-autumn-2020-2'], gen:genSnail },
  { id:56, op:'w', grp:'word', d:5, eq:'Кофата', desc:'Filling a vessel until the two possible buckets tell apart', also:['mbg-autumn-2020-2'], gen:genBucket },
  { id:33, op:'w', grp:'word', d:5, eq:'Цветя', desc:'Petals of three kinds adding to a total', also:['mbg-autumn-2024-2'], gen:genFlowers },
  { id:87, op:'w', grp:'word', src:'mbg-winter-2024', d:3, eq:'Балоните', desc:'A total shared out: a few with several each, the rest with one', also:['mbg-winter-2023-2'], gen:genBalloons },
  { id:88, op:'w', grp:'word', src:'mbg-winter-2024', d:4, eq:'След 10 години', desc:'An age from how many times older someone will be', gen:genAge },
  { id:96, op:'w', grp:'word', src:'kms-2025', d:3, eq:'Всеки ден повече', desc:'The same amount more each day, and a few of the days added', gen:genDaily },
  { id:98, op:'w', grp:'word', needs:[10], src:'kms-2025', d:5, eq:'Градът на Дядо Коледа', desc:'A route, a ticket table, and the change counted out', gen:genSanta },
  { id:62, op:'w', grp:'word', needs:[10, 59], grade:3, d:3, eq:'+ 9 и − 9', desc:'Two long expressions that differ only at the end', gen:genPmGap },
  { id:78, op:'w', grp:'word', needs:[39], grade:3, d:4, eq:'Портокалите', desc:'Sharing out two ways: short with one, exact with the other', gen:genTwoShare },
  { id:20, op:'w', grp:'geo', d:3, eq:'A, B, C', desc:'Along a line, right then left — how far apart?', also:['mbg-autumn-2025-2'], gen:genLine },
  { id:40, op:'w', grp:'geo', d:3, eq:'AD = ?', desc:'Overlapping lengths along a line', also:['mbg-autumn-2021-2', 'mbg-autumn-2023-2'], gen:genSeg },
  { id:32, op:'w', grp:'geo', d:3, eq:'Ленти', desc:'Centimetres, decimetres and metres', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2024-2'], gen:genRibbon },
  { id:52, op:'w', grp:'geo', d:3, eq:'Изрязан ъгъл', desc:'A corner cut from a rectangle — its sides and its outline', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2'], gen:genStep },
  { id:31, op:'w', grp:'geo', d:4, eq:'Дръвчета', desc:'Trees in a row: the gaps are one fewer, and the units may not match', also:['mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2024-2'], gen:genTrees },
  { id:21, op:'w', grp:'geo', d:4, eq:'Обиколка', desc:'Squares, sheets and triangles — sides and perimeters', also:['mbg-winter-2023-2', 'mbg-autumn-2020-2', 'mbg-autumn-2021-2', 'mbg-autumn-2022-2', 'mbg-autumn-2023-2', 'mbg-autumn-2025-2'], gen:genSqCut },
  { id:22, op:'w', grp:'geo', needs:[21], d:4, eq:'Обща страна', desc:'Two figures share an edge — what it costs the outline', also:['mbg-autumn-2022-2', 'mbg-autumn-2024-2', 'mbg-autumn-2025-2'], gen:genShared },
  { id:34, op:'w', grp:'geo', needs:[19], d:4, eq:'Оцветени', desc:'Paint whole rows and columns — what is left', also:['mbg-autumn-2024-2'], gen:genPaint },
  { id:19, op:'w', grp:'geo', d:4, eq:'Правоъгълници', desc:'How many rectangles in the grid hold the ant', also:['mbg-winter-2023-2', 'mbg-autumn-2023-2', 'mbg-autumn-2025-2', 'mbg-winter-2024-2'], gen:genRects },
  { id:41, op:'w', grp:'geo', needs:[40], d:4, eq:'Три точки', desc:'Three points on a line — two answers', also:['mbg-autumn-2023-2'], gen:genThree },
  { id:84, op:'w', grp:'geo', needs:[21], src:'mbg-winter-2024', d:4, eq:'Режем квадрати', desc:'Cut the biggest square off a sheet, again and again', gen:genSqOff },
  { id:85, op:'w', grp:'geo', needs:[21], src:'mbg-winter-2024', d:4, eq:'Четири правоъгълника', desc:'A figure of four equal rectangles, from its perimeter', gen:genPinwheel },
  { id:90, op:'w', grp:'geo', src:'kms-2025', d:3, eq:'Равнобедрени', desc:'Triangles on a grid: which have two equal sides', gen:genIsoTri },
  { id:91, op:'w', grp:'geo', needs:[32], src:'kms-2025', d:2, eq:'Обиколка в дм', desc:'A rectangle\'s perimeter, asked in another unit', also:['mbg-winter-2023-2'], gen:genRectDm },
  { id:97, op:'w', grp:'geo', needs:[21], src:'kms-2025', d:3, eq:'Бедро и основа', desc:'An isosceles triangle built from a square\'s side', gen:genIsoPerim },
  { id:71, op:'w', grp:'geo', needs:[20], grade:3, d:1, eq:'Селищата', desc:'A midpoint, and a place a few kilometres from it', gen:genMidPt },
  { id:70, op:'w', grp:'geo', needs:[31], grade:3, d:2, eq:'Точки на отсечка', desc:'Points that cut a segment into equal parts, plus a piece beyond', gen:genSegPts },
  { id:72, op:'w', grp:'geo', needs:[21], grade:3, d:3, eq:'Триъгълник и квадрат', desc:'A triangle\'s side against a square\'s perimeter, in millimetres', gen:genTriVsSq },
  { id:73, op:'w', grp:'geo', needs:[21], grade:3, d:4, eq:'Плочки', desc:'Rectangles made of two squares, and the big rectangle they tile', gen:genPlates },
  { id:69, op:'w', grp:'geo', needs:[21], grade:3, d:4, eq:'Звезда', desc:'Equilateral triangles on the sides of a square, and the square\'s perimeter', gen:genStar },
];
// 3rd-grade rows are rated against each other, not on the 2nd-grade scale: multiplication is
// the ordinary operation there, so their d spreads over 1–5 like the 2nd grade's does.
// Where the levels come from: the plain sums (take away, add) are basics, the drill under
// everything; every other level is modelled on a task from Математика без граници, autumn
// round, 2nd grade unless its row says grade:3. A paper is one source and grade together,
// keyed 'mbg-autumn-2' or 'mbg-winter-2024-2'. A level whose task also turns up on another
// paper lists that paper in also:[…]; it is still one level, rated once — a task that is
// easier or harder on the other paper is a level of its own, not a tag.
LEVELS.forEach(l => {
  l.src = l.src || (l.op === '-' || l.op === '+' ? 'basics' : 'mbg-autumn'); l.grade = l.grade || 2;
  l.papers = [l.src === 'basics' ? 'basics' : l.src + '-' + l.grade].concat(l.also || []);
  // how many real, dated papers ask it — the ones she is likeliest to meet again
  l.freq = l.papers.filter(p => /-\d{4}-\d+$/.test(p)).length;
});
// Picker sections, in the order they appear. Levels inside each are sorted easiest
// first in the LEVELS table above.
const PICK_GROUPS = [
  { nm:'Take away',          has: l => l.op === '-' },
  { nm:'Add',                has: l => l.op === '+' },
  { nm:'Chains',             has: l => l.grp === 'chain' },
  { nm:'Counting',           has: l => l.grp === 'count' },
  { nm:'Numbers and digits', has: l => l.grp === 'num' },
  { nm:'Sequences',          has: l => l.grp === 'seq' },
  { nm:'Find the value',     has: l => l.grp === 'find' },
  { nm:'Word problems',      has: l => l.grp === 'word' },
  { nm:'Shapes and lines',   has: l => l.grp === 'geo' }
];
const LEVEL_NAME = {}, LEVEL_OP = {};
LEVELS.forEach(l => { LEVEL_NAME[l.id] = l.eq; LEVEL_OP[l.id] = l.op; });
