// Question kind 'erase': level 15 Кое изтрих? — Spot the number a few more — or a few less — than another.

// Задача 8: exactly one number in the list is d more than another one. Generated by
// rejection so there is never a second candidate to argue about.
import { KIND, SLOT, bgList, rnd, tr } from '../js/core.js';
export function genErase(){
  for(;;){
    const d = 2 + rnd(5);                                // up to 6: Есен 2024 asked «по-малко с 6»
    const set = [];
    while(set.length < 5){ const v = 2 + rnd(18); if(set.indexOf(v) < 0) set.push(v); }
    set.sort((x,y) => x - y);
    const hits = set.filter(x => set.indexOf(x + d) >= 0).map(x => x + d);
    if(hits.length !== 1) continue;
    const bigger = Math.random() < 0.5;                 // "по-голямо с d" or "по-малко с d"
    const gone = bigger ? hits[0] : hits[0] - d;
    return {kind:'erase', set, d, bigger, gone, ans: set.reduce((t,v) => t + v, 0) - gone};
  }
}

function drawErase(q){
  const which = q.bigger
    ? tr('Изтрих едно от числата, което е <b>по-голямо</b> с <span class="num">' + q.d + '</span> от друго от тях.',
         'Одне з чисел, яке на <span class="num">' + q.d + '</span> <b>більше</b> за інше з них, стерли.')
    : tr('Едното от тях, което е <b>по-малко</b> с <span class="num">' + q.d + '</span> от друго от тях, изтрих.',
         'Одне з них, яке на <span class="num">' + q.d + '</span> <b>менше</b> за інше з них, стерли.');
  return '<div class="ask">' + tr('Записах числата', 'Записали числа') + ' <span class="num">' + bgList(q.set) + '</span>. ' + which +
    tr(' Пресметнете сбора на останалите числа.', ' Обчисліть суму решти чисел.') + '</div>' +
    '<div class="line xl">' + SLOT + '</div>';
}
function eqErase(q){
  return bgList(q.set) + tr(', изтрито ', ', стерто ') + q.gone + ' → ' + q.ans;
}
function whyErase(q, full){
  if(!full) return q.bigger ? tr('Кое число е точно толкова по-голямо от друго?', 'Яке число рівно на стільки більше за інше?')
                            : tr('Кое число е точно толкова по-малко от друго?', 'Яке число рівно на стільки менше за інше?');
  return '<b>' + q.gone + ' = ' + (q.bigger ? (q.gone - q.d) + ' + ' + q.d : (q.gone + q.d) + ' − ' + q.d) +
    '</b> &nbsp;→&nbsp; ' + tr('изтриваме ', 'стираємо ') + q.gone +
    ' &nbsp;→&nbsp; ' + q.set.filter(v => v !== q.gone).join(' + ') + ' = ' + q.ans;
}
KIND.erase = { draw:drawErase, eq:eqErase, why:whyErase };
